### ISSUE TITLE
Sharing idea

### ISSUE THREAD

**Issue by Grant-Smith-74** [Pipits/pipit-sharing#1]
Would be great if pipit-sharing included email sharing.

**Comment by husseinalhammad** [comment]
Hello Grant,

Since v1.1 the app has support for email sharing links (mailto) as stated in the [changelog](https://grabapipit.com/pipits/apps/sharing/docs/changelog) and the [releases notes](https://github.com/Pipits/pipit-sharing/releases).

It seems I have failed to update the documentation. So thanks for reminding me. I'll let you know when the docs is updated.

**Comment by montlewis** [comment]
hey, nice job on this!

**Comment by husseinalhammad** [comment]
Thanks, @montlewis. Releasing v1.2 soon with a new feature.

---

Sorry @granttransition I haven't got around to updating the docs yet. You'll basically use:

```
<a href="<perch:sharing id="email" />" >Email to a friend</a>
```

You can also use the fields with the following IDs to add a subject and a body to the email:

* `sharing_email_subject`
* `sharing_email_desc`

**Comment by husseinalhammad** [comment]
Documentation has been updated.

https://grabapipit.com/pipits/apps/sharing/docs/templates/#email
